# Generated by Django 3.0.6 on 2020-06-06 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.IntegerField(choices=[(5, 'Male'), (-161, 'Female')], default=5)),
                ('startAge', models.SmallIntegerField()),
                ('currentWeight', models.FloatField()),
                ('weightUnit', models.FloatField(choices=[(2.20462, 'Pounds'), (1, 'Kilograms')], default=1)),
                ('startHeight', models.FloatField()),
                ('heightUnit', models.FloatField(choices=[(2.54, 'Inches'), (1, 'Centimeters')], default=1)),
                ('activityLevel', models.FloatField(choices=[(1.2, 'Sedentary'), (1.375, 'Light Activity'), (1.55, 'Moderately Active'), (1.725, 'Very Active'), (1.9, 'Extremely Active')], default=1.2)),
                ('startBMR', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserWeights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldWeights', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customProfile.CustomUser')),
            ],
        ),
    ]
