# Generated by Django 3.0.6 on 2020-06-06 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customProfile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='startHeight',
            new_name='height',
        ),
    ]
