# Generated by Django 3.0.6 on 2020-06-19 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customProfile', '0002_auto_20200606_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='startBMR',
            new_name='BMR',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='startAge',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='currentWeight',
            new_name='weight',
        ),
    ]
