# Generated by Django 3.0.6 on 2020-06-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customProfile', '0003_auto_20200619_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='BMR',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
