# Generated by Django 3.0.6 on 2020-06-19 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recurapp', '0009_auto_20200530_1211'),
        ('customProfile', '0004_auto_20200619_0534'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConsumedFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(auto_now_add=True)),
                ('meal', models.CharField(choices=[('b', 'Breakfast'), ('l', 'Lunch'), ('d', 'Dinner'), ('s', 'Snack')], default='b', max_length=2)),
                ('takenPortion', models.FloatField(default=1.0)),
                ('returnedPortion', models.FloatField(default=0.0)),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recurapp.MainDesc')),
                ('servingSize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recurapp.Foodweights')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customProfile.CustomUser')),
            ],
        ),
    ]
