# Generated by Django 3.0.6 on 2020-07-12 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customProfile', '0006_auto_20200619_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='BMR',
        ),
    ]
