# Generated by Django 3.0.6 on 2020-05-25 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foodportiondesc',
            fields=[
                ('portion_code', models.IntegerField(db_column='Portion_code', primary_key=True, serialize=False)),
                ('portion_description', models.CharField(db_column='Portion_description', max_length=120)),
                ('start_date', models.DateTimeField(db_column='Start_date')),
                ('end_date', models.DateTimeField(db_column='End_date')),
            ],
            options={
                'db_table': 'foodportiondesc',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MainDesc',
            fields=[
                ('food_code', models.IntegerField(db_column='Food_code', primary_key=True, serialize=False)),
                ('main_food_description', models.CharField(db_column='Main_food_description', max_length=200)),
                ('fortification_identifier_code', models.CharField(blank=True, db_column='Fortification_identifier_code', max_length=2, null=True)),
                ('wweia_category_code', models.IntegerField(db_column='WWEIA_Category_code')),
                ('wweia_category_description', models.CharField(db_column='WWEIA_Category_description', max_length=80)),
                ('start_date', models.DateTimeField(db_column='Start_date')),
                ('end_date', models.DateTimeField(db_column='End_date')),
            ],
            options={
                'db_table': 'MainDesc',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SrFoodDes',
            fields=[
                ('ndb_no', models.IntegerField(db_column='NDB_No', primary_key=True, serialize=False)),
                ('fdgrp_cd', models.CharField(db_column='FdGrp_Cd', max_length=4)),
                ('long_desc', models.CharField(db_column='Long_Desc', max_length=200)),
                ('shrt_desc', models.CharField(db_column='Shrt_Desc', max_length=60)),
                ('comname', models.CharField(blank=True, db_column='ComName', max_length=100, null=True)),
                ('manufacname', models.CharField(blank=True, db_column='ManufacName', max_length=65, null=True)),
                ('survey', models.CharField(blank=True, db_column='Survey', max_length=1, null=True)),
                ('ref_desc', models.CharField(blank=True, db_column='Ref_Desc', max_length=135, null=True)),
                ('refuse', models.SmallIntegerField(db_column='Refuse', null=True)),
                ('sciname', models.CharField(blank=True, db_column='SciName', max_length=65, null=True)),
                ('n_factor', models.DecimalField(blank=True, db_column='N_Factor', decimal_places=2, max_digits=3, null=True)),
                ('pro_factor', models.DecimalField(blank=True, db_column='Pro_Factor', decimal_places=2, max_digits=3, null=True)),
                ('fat_factor', models.DecimalField(blank=True, db_column='Fat_Factor', decimal_places=2, max_digits=3, null=True)),
                ('cho_factor', models.DecimalField(blank=True, db_column='CHO_Factor', decimal_places=2, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'SrFoodDes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subcodedesc',
            fields=[
                ('subcode', models.IntegerField(db_column='Subcode', primary_key=True, serialize=False)),
                ('subcode_description', models.CharField(db_column='Subcode_description', max_length=80)),
                ('start_date', models.DateTimeField(db_column='Start_date')),
                ('end_date', models.DateTimeField(db_column='End_date')),
            ],
            options={
                'db_table': 'subcodedesc',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_num', models.SmallIntegerField(db_column='Seq_num')),
                ('ingredient_code', models.IntegerField(db_column='Ingredient_code')),
                ('ingredient_description', models.CharField(db_column='Ingredient_description', max_length=240)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=4, max_digits=8)),
                ('measure', models.CharField(blank=True, db_column='Measure', max_length=3, null=True)),
                ('path', models.CharField(blank=True, max_length=100, null=True)),
                ('retention_code', models.SmallIntegerField(db_column='Retention_code')),
                ('ingredient_weight', models.DecimalField(db_column='Ingredient_weight', decimal_places=4, max_digits=8)),
                ('start_date', models.DateTimeField(db_column='Start_date')),
                ('end_date', models.DateTimeField(db_column='End_date')),
                ('food_code', models.ForeignKey(db_column='Food_code', on_delete=django.db.models.deletion.CASCADE, related_name='Ingreds', to='recurapp.MainDesc')),
                ('portion_code', models.ForeignKey(db_column='Portion_code', on_delete=django.db.models.deletion.CASCADE, to='recurapp.Foodportiondesc')),
            ],
            options={
                'db_table': 'Ingredients',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Foodweights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_num', models.SmallIntegerField(blank=True, db_column='Seq_num', null=True)),
                ('portion_weight', models.DecimalField(blank=True, db_column='Portion_weight', decimal_places=2, max_digits=4, null=True)),
                ('start_date', models.DateTimeField(db_column='Start_date')),
                ('end_date', models.DateTimeField(db_column='End_date')),
                ('food_code', models.ForeignKey(db_column='Food_code', on_delete=django.db.models.deletion.CASCADE, related_name='Weights', to='recurapp.MainDesc')),
                ('portion_code', models.ForeignKey(db_column='Portion_code', on_delete=django.db.models.deletion.CASCADE, to='recurapp.Foodportiondesc')),
                ('subcode', models.ForeignKey(blank=True, db_column='Subcode', null=True, on_delete=django.db.models.deletion.CASCADE, to='recurapp.Subcodedesc')),
            ],
            options={
                'db_table': 'foodweights',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Foodsubcodelinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, db_column='Start_date', null=True)),
                ('end_date', models.DateTimeField(blank=True, db_column='End_date', null=True)),
                ('food_code', models.ForeignKey(db_column='Food_code', on_delete=django.db.models.deletion.CASCADE, to='recurapp.MainDesc')),
                ('subcode', models.ForeignKey(db_column='Subcode', on_delete=django.db.models.deletion.CASCADE, related_name='subdescs', to='recurapp.Subcodedesc')),
            ],
            options={
                'db_table': 'foodsubcodelinks',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AddDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_num', models.SmallIntegerField(db_column='Seq_num')),
                ('additional_food_description', models.CharField(blank=True, db_column='Additional_food_description', max_length=80, null=True)),
                ('start_date', models.DateTimeField(db_column='Start_date')),
                ('end_date', models.DateTimeField(db_column='End_date')),
                ('food_code', models.ForeignKey(db_column='Food_code', on_delete=django.db.models.deletion.CASCADE, related_name='AddDescs', to='recurapp.MainDesc')),
            ],
            options={
                'db_table': 'AddDesc',
                'managed': True,
            },
        ),
    ]
