# Generated by Django 3.0.6 on 2020-05-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodweights',
            name='portion_weight',
            field=models.DecimalField(blank=True, db_column='Portion_weight', decimal_places=2, max_digits=5, null=True),
        ),
    ]
