# Generated by Django 3.0.6 on 2020-05-25 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recurapp', '0003_auto_20200525_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodweights',
            name='portion_code',
            field=models.ForeignKey(db_column='Portion_code', on_delete=django.db.models.deletion.CASCADE, related_name='portiondescs', to='recurapp.Foodportiondesc'),
        ),
    ]
