# Generated by Django 3.0.6 on 2020-05-25 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recurapp', '0006_fnddsnutval_nutdesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodweights',
            name='url_weight',
            field=models.IntegerField(blank=True, db_column='Url_weight', null=True),
        ),
        migrations.AlterField(
            model_name='fnddsnutval',
            name='nutrient_code',
            field=models.ForeignKey(blank=True, db_column='Nutrient_code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NutrientDescriptions', to='recurapp.Nutdesc'),
        ),
    ]
