# Generated by Django 3.0.6 on 2020-05-25 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recurapp', '0007_auto_20200525_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fnddsnutval',
            name='food_code',
            field=models.ForeignKey(db_column='Food_code', on_delete=django.db.models.deletion.CASCADE, related_name='NutrientValues', to='recurapp.MainDesc'),
        ),
    ]
