# Generated by Django 3.0.6 on 2020-05-30 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recurapp', '0008_auto_20200525_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maindesc',
            options={'managed': True, 'ordering': ['food_code']},
        ),
    ]
